poollevel-render
PhoboSys/pm-stickchart pull request #35
Opened 2022-05-09 09:05 UTC by boyko-pavlo

2022-05-09 17:17 UTC, mishadev requested changes

2022-05-09 17:17 UTC, mishadev commented on src/rendering/renderers/pool/PoolRenderer.ts
>          const { torusstyle } = style
I think there should be couple simple changes in this file
1. You should read texture from `context.textures.get(...)` and add it into `coveredNameStyle.texture`
```
const { coveredNameStyle } = style
coveredNameStyle.texture = context.textures.get(MAP_TO_TEXTURES[pool.level])

const [coveredName, coveredNameState] = this.get('cover'+title, () => GraphicUtils.createCoveredText(
            title,
            [x + coverpadding, paddingTop],
            coveredNameStyle,
        ), [pool.level])
```
To implement that right you should add dependency to `this.get(...)` function in order to re-init the graphic

2. You should add logic to `createCoveredText` function to apply texture it was passed to the function via `styles`

3. All textures should be to TextureStorage

4. Gradient angle is setted by start and end line coordinates

2022-05-11 11:29 UTC, mishadev requested changes

2022-05-11 11:29 UTC, mishadev commented on src/StickChart.ts
> +            renderer: this.application.renderer,
we don't need renderer in the context

2022-05-11 11:29 UTC, mishadev commented on src/rendering/renderers/pool/PoolLockRenderer.ts
> +            cover.position.y = this.coverStyle.paddingTop
You should update position x and y on each render
Because scale of the screen could change

2022-05-11 11:29 UTC, mishadev commented on src/rendering/renderers/pool/PoolLockRenderer.ts
> +        torus.position.x = x
torus.position.set(x, cover.position.y + cover.height)

2022-05-11 19:52 UTC, mishadev approved these changes

2022-05-12 18:11 UTC, metaferryman approved these changes

2022-05-12 20:38 UTC, mishadev approved these changes

2022-05-12 20:38 UTC, merged